### ISSUE TITLE
KissFFT -> FFTW

### ISSUE THREAD

**Issue by AlexVestin** [AlexVestin/musicvid.org#1]
KissFFT 16k fft > 7ms on laptop, could probably be halved by FFTW

**Comment by jagger2048** [comment]
I think use fftw in browser is not a good choice, a single file library is better.

**Comment by AlexVestin** [comment]
@jagger2048 Been a while since I used fftw, so I forget how the structure was. Do you have any suggestion for replacements? 

Also I looked in your repo with fft-simd, and since WebAssembly simd support is on its way, do you think it would be something to go for?

**Comment by jagger2048** [comment]
Hi, the fftw is the faster fft open source algorithm, but it is a bit complex and requires more dependencies. 
I'm not family with WebAssembly, I find a WebAssembly implementation of kissFFT, https://github.com/AWSM-WASM/PulseFFT. It is derived by the Javascript engine although it has not supported the SIMD.  
As far as I know, the kissFFT library can support SIMD, it is a direction that use  WebAssembly simd to port the library.
