### ISSUE TITLE
Can't open long music

### ISSUE THREAD

**Issue by DaWe35** [AlexVestin/musicvid.org#2]
Hello!
I want to animate my 4-hour mix, but importing the 350 MB mp3 takes forever. I downloaded the desktop version, but it crashes when my computer exceed the 100% used RAM. Is there any solution, or a linux-based command line version to do that on a VPS?

**Comment by AlexVestin** [comment]
No, I don't think that would be feasible with the current implementations. I think the best way to go about this would be to first split the audio file and export it and then combine the resulting videos with FFmpeg or something similar

**Comment by DaWe35** [comment]
> No, I don't think that would be feasible with the current implementations. I think the best way to go about this would be to first split the audio file and export it and then combine the resulting videos with FFmpeg or something similar

Thank you, that's a good idea!

Is it really important to put all that stuff into RAM? Just because I tried https://isaiah658.github.io, and it worked with any length of the video (ok, maybe this script is much more simpler, but rendering is rendering).

**Comment by AlexVestin** [comment]
>Is it really important to put all that stuff into RAM?

Yes and no, this project doesn't use the web audio apis fft, and has to decode and store the entire decoded audio file in memory, which gets quite large. 

The project you linked uses WebRTC canvas recording, which works well but encodes in real time, so the video quality might vary greatly. I tried that approach early in the project and couldnt get it to keep the quality high. Here's a video of musicvid using that implemenation https://www.youtube.com/watch?v=ge75IBVbYOI

**Comment by sndrjhlncgr** [comment]
go to chrome://flags/ then enable the **Override software rendering list**  thats all. if youre using google chrome.
