### ISSUE TITLE
Can't Compile

### ISSUE THREAD

**Issue by 0xf0xx0** [AlexVestin/musicvid.org#3]
Trying to compile from master branch and keep getting errors like 

> ./src/editor/animation/materials/NoiseMaterial.js
Module not found: Can't resolve '../shaders/licensed/Noise' in '/Users/gingkathfox/musicvid.org/src/editor/animation/materials'

Any reason the `licensed` folder doesnt exist?

**Comment by AlexVestin** [comment]
Yes, it was a part of an agreement not to include them with the source code. 
Might be able to just flip this and compile it
https://github.com/AlexVestin/musicvid.org/blob/4dfb55dc93546ac9d72f82d9b8246aa7b1174123/src/editor/animation/items/index.js#L81

**Comment by 0xf0xx0** [comment]
aight, ill do that.
