### ISSUE TITLE
How do smooth "Audio impact Automation"?

### ISSUE THREAD

**Issue by vitalijm** [AlexVestin/musicvid.org#5]
Thanks for sharing this huge project with others.

1. Question: How we can do smooth "Audio impact Automation" for any prop, especially for Background-__scale?

2. If i not typing value in transform field then: its jumping  from 0 to 1, can I type some range, like from 1 to 1.3? If I typing some value in transform field: it without smooth animation working.

2. Question: Exist some documentation how to use your web app? Will be it created in the future?

Thanks

**Comment by AlexVestin** [comment]
Hey!
1. you can check out the [tutorial](https://musicvid.org/tutorial/audio_analysers/impact) for the impact analyzer, theres a tab for the smoothing. Also there's a demo on the page if you want visualize what the settings are doing.
2. I think that's only a visual issue from dat.gui (or more likely my usage of the library), values between the step are still usable, but the number in the box just isn't updating.
3. There's a [tutorial section](https://musicvid.org/tutorial) which covers some of it, but it's unlikely to be expanded

**Comment by vitalijm** [comment]
Thank You
